
package com.hleast.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "staffServer", targetNamespace = "http://webservice.hleast.com/", wsdlLocation = "http://localhost:8890/staffServer?wsdl")
public class StaffServer
    extends Service
{

    private final static URL STAFFSERVER_WSDL_LOCATION;
    private final static WebServiceException STAFFSERVER_EXCEPTION;
    private final static QName STAFFSERVER_QNAME = new QName("http://webservice.hleast.com/", "staffServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8890/staffServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STAFFSERVER_WSDL_LOCATION = url;
        STAFFSERVER_EXCEPTION = e;
    }

    public StaffServer() {
        super(__getWsdlLocation(), STAFFSERVER_QNAME);
    }

    public StaffServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), STAFFSERVER_QNAME, features);
    }

    public StaffServer(URL wsdlLocation) {
        super(wsdlLocation, STAFFSERVER_QNAME);
    }

    public StaffServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STAFFSERVER_QNAME, features);
    }

    public StaffServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StaffServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "TestWebServicePort")
    public WebInterface getTestWebServicePort() {
        return super.getPort(new QName("http://webservice.hleast.com/", "TestWebServicePort"), WebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "TestWebServicePort")
    public WebInterface getTestWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.hleast.com/", "TestWebServicePort"), WebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STAFFSERVER_EXCEPTION!= null) {
            throw STAFFSERVER_EXCEPTION;
        }
        return STAFFSERVER_WSDL_LOCATION;
    }

}
