
package com.hleast.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebInterface", targetNamespace = "http://webservice.hleast.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebInterface {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.hleast.com/", className = "com.hleast.webservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.hleast.com/", className = "com.hleast.webservice.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "userName", targetNamespace = "")
        String userName);

    /**
     * 
     * @param time
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStaffs", targetNamespace = "http://webservice.hleast.com/", className = "com.hleast.webservice.GetStaffs")
    @ResponseWrapper(localName = "getStaffsResponse", targetNamespace = "http://webservice.hleast.com/", className = "com.hleast.webservice.GetStaffsResponse")
    public String getStaffs(
        @WebParam(name = "time", targetNamespace = "")
        int time);

}
